### ISSUE TITLE
getCurrentItem()；give back a wrong number

### ISSUE THREAD

**Issue by liyuhaolol** [angeldevil/AutoScrollViewPager#2]
if you getCurrentItem immediately，while give back a wrong number

        Log.e("debug",mViewPager.getCurrentItem()+"");  `this while log item totalCount -1`
        Thread t = new Thread(new Runnable() {
            @Override
            public void run() {
                try {
                    while (true){

                        Log.e("debug",mViewPager.getCurrentItem()+"");` this while log item totalCount -1 one time then log number is right`
                        Thread.sleep(1000);
                    }
                } catch (InterruptedException e) {
                    e.printStackTrace();
                }
            }
        });
        t.start();

**Comment by angeldevil** [comment]
Fixed in commit https://github.com/angeldevil/AutoScrollViewPager/commit/599c8fe7aa6006f8a6b5179979603775519c7bac, Version 1.0.7
